
version: '3.5'

services:
  frontend:
    container_name: usabi_front
    image: felipesantanasb/usabivalid:0.4
    depends_on:
      - backend
    networks:
      - minha-rede
    ports:
      - "80:80"
      - "443:443"

  backend:
    container_name: usabi_back
    image: felipesantanasb/usabivalid-back:0.2
    ports:
      - "8084:8084"
    networks:
      - minha-rede
    

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - minha-rede
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - minha-rede
    restart: unless-stopped

networks:
  minha-rede:
    driver: bridge

volumes:
    postgres:
        external:
            name: "pasta"
    pgadmin: